sudo: False
language: generic
matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      env: TRAVIS_PYTHON_VERSION="3.9"
    - os: linux
      env: TRAVIS_PYTHON_VERSION="3.8"
    - os: linux
      env: TRAVIS_PYTHON_VERSION="3.7"
    - os: linux
      env: TRAVIS_PYTHON_VERSION="3.6"
    - os: linux
      env: TRAVIS_PYTHON_VERSION="3.5"
    - os: osx
      env: TRAVIS_PYTHON_VERSION="3.9"
    - os: osx
      env: TRAVIS_PYTHON_VERSION="3.8"
    - os: osx
      env: TRAVIS_PYTHON_VERSION="3.7"
    - os: osx
      env: TRAVIS_PYTHON_VERSION="3.6"
    - os: osx
      env: TRAVIS_PYTHON_VERSION="3.5"
install:
  # Install conda
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-env python=$TRAVIS_PYTHON_VERSION pytest pandas matplotlib
  - source activate test-env
  - pip install pytest-cov
  - pip install codecov
  - pip install -e '.[extras]'
script:
  - make
after_success:
  - codecov
notifications:
  email: false
